# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_design.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1605, 1059)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_Main = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Main.setGeometry(QtCore.QRect(30, 30, 111, 51))
        self.btn_Main.setObjectName("btn_Main")
        self.btn_Info = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Info.setGeometry(QtCore.QRect(160, 30, 111, 51))
        self.btn_Info.setObjectName("btn_Info")
        self.lbl_mainView = QtWidgets.QLabel(self.centralwidget)
        self.lbl_mainView.setGeometry(QtCore.QRect(30, 120, 1271, 651))
        self.lbl_mainView.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_mainView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_mainView.setMidLineWidth(1)
        self.lbl_mainView.setScaledContents(True)
        self.lbl_mainView.setObjectName("lbl_mainView")
        self.lbl_sideView_0 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sideView_0.setGeometry(QtCore.QRect(1320, 120, 261, 201))
        self.lbl_sideView_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbl_sideView_0.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_sideView_0.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_sideView_0.setMidLineWidth(1)
        self.lbl_sideView_0.setScaledContents(True)
        self.lbl_sideView_0.setObjectName("lbl_sideView_0")
        self.lbl_sideView_1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sideView_1.setGeometry(QtCore.QRect(1320, 340, 261, 201))
        self.lbl_sideView_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbl_sideView_1.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_sideView_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_sideView_1.setMidLineWidth(1)
        self.lbl_sideView_1.setScaledContents(True)
        self.lbl_sideView_1.setObjectName("lbl_sideView_1")
        self.lbl_sideView_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sideView_2.setGeometry(QtCore.QRect(1320, 560, 261, 211))
        self.lbl_sideView_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbl_sideView_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_sideView_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_sideView_2.setMidLineWidth(1)
        self.lbl_sideView_2.setScaledContents(True)
        self.lbl_sideView_2.setObjectName("lbl_sideView_2")
        self.txt_Log = QtWidgets.QTextBrowser(self.centralwidget)
        self.txt_Log.setGeometry(QtCore.QRect(30, 800, 1271, 192))
        self.txt_Log.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.txt_Log.setObjectName("txt_Log")
        self.mdi_sideView_0 = QtWidgets.QMdiArea(self.centralwidget)
        self.mdi_sideView_0.setGeometry(QtCore.QRect(1320, 320, 260, 8))
        self.mdi_sideView_0.setToolTip("")
        self.mdi_sideView_0.setFrameShape(QtWidgets.QFrame.Box)
        self.mdi_sideView_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mdi_sideView_0.setLineWidth(0)
        brush = QtGui.QBrush(QtGui.QColor(0, 200, 0, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdi_sideView_0.setBackground(brush)
        self.mdi_sideView_0.setObjectName("mdi_sideView_0")
        self.mdi_sideView_1 = QtWidgets.QMdiArea(self.centralwidget)
        self.mdi_sideView_1.setGeometry(QtCore.QRect(1320, 540, 260, 8))
        self.mdi_sideView_1.setFrameShape(QtWidgets.QFrame.Box)
        self.mdi_sideView_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mdi_sideView_1.setLineWidth(0)
        brush = QtGui.QBrush(QtGui.QColor(0, 200, 0, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdi_sideView_1.setBackground(brush)
        self.mdi_sideView_1.setObjectName("mdi_sideView_1")
        self.mdi_sideView_2 = QtWidgets.QMdiArea(self.centralwidget)
        self.mdi_sideView_2.setGeometry(QtCore.QRect(1320, 770, 260, 8))
        self.mdi_sideView_2.setFrameShape(QtWidgets.QFrame.Box)
        self.mdi_sideView_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mdi_sideView_2.setLineWidth(0)
        brush = QtGui.QBrush(QtGui.QColor(0, 200, 0, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdi_sideView_2.setBackground(brush)
        self.mdi_sideView_2.setObjectName("mdi_sideView_2")
        self.mdi_mainView = QtWidgets.QMdiArea(self.centralwidget)
        self.mdi_mainView.setGeometry(QtCore.QRect(30, 770, 1270, 8))
        self.mdi_mainView.setFrameShape(QtWidgets.QFrame.Box)
        self.mdi_mainView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mdi_mainView.setLineWidth(0)
        brush = QtGui.QBrush(QtGui.QColor(0, 200, 0, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdi_mainView.setBackground(brush)
        self.mdi_mainView.setObjectName("mdi_mainView")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(1320, 830, 261, 51))
        self.groupBox.setObjectName("groupBox")
        self.slider_sensitivity = QtWidgets.QSlider(self.groupBox)
        self.slider_sensitivity.setGeometry(QtCore.QRect(10, 20, 241, 22))
        self.slider_sensitivity.setMaximum(19)
        self.slider_sensitivity.setPageStep(1)
        self.slider_sensitivity.setProperty("value", 4)
        self.slider_sensitivity.setOrientation(QtCore.Qt.Horizontal)
        self.slider_sensitivity.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_sensitivity.setTickInterval(1)
        self.slider_sensitivity.setObjectName("slider_sensitivity")
        self.checkBox_drawBoxes = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_drawBoxes.setGeometry(QtCore.QRect(1320, 800, 261, 20))
        self.checkBox_drawBoxes.setObjectName("checkBox_drawBoxes")
        self.checkBox_drawGrid = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_drawGrid.setGeometry(QtCore.QRect(1320, 890, 261, 20))
        self.checkBox_drawGrid.setObjectName("checkBox_drawGrid")
        self.checkBox_drawStaticObjects = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_drawStaticObjects.setGeometry(QtCore.QRect(1320, 910, 261, 20))
        self.checkBox_drawStaticObjects.setObjectName("checkBox_drawStaticObjects")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1605, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_Main.setText(_translate("MainWindow", "Main"))
        self.btn_Info.setText(_translate("MainWindow", "Info"))
        self.lbl_mainView.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sideView_0.setToolTip(_translate("MainWindow", "Side View 1"))
        self.lbl_sideView_0.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sideView_1.setToolTip(_translate("MainWindow", "Side View 2"))
        self.lbl_sideView_1.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sideView_2.setToolTip(_translate("MainWindow", "Side View 3"))
        self.lbl_sideView_2.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox.setTitle(_translate("MainWindow", "YOLO Sensitivity"))
        self.checkBox_drawBoxes.setText(_translate("MainWindow", "YOLO Objects"))
        self.checkBox_drawGrid.setText(_translate("MainWindow", "Grid"))
        self.checkBox_drawStaticObjects.setText(_translate("MainWindow", "Static Objects"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
